site_name: KGIS
site_url: http://kgis.be
site_author: Kay Warrie
site_description: Website van KGIS GIS-consulting.

copyright: 'Copyright &copy; 2018 Kay Warrie (<em><a href="mailto:kaywarrie@gmail.com" >Contacteer mij</a></em>)<br/>Julius de Geyterstraat 142, 2610 Antwerpen'

nav:
    - "KGIS": index.md
    - "Over mij": about.md
    - "Projecten": projects.md
        
use_directory_urls: false
  
theme:
  name: null
  favicon: 'img/favicon.ico'
  custom_dir: 'material'
  language: 'nl'
  include_search_page: false
  search_index_only: true
  palette:
    primary: 'blue grey'
    accent: 'amber'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  icon: 'cloud'
  feature:
    tabs: true
  logo: 'img/Layers.png'
  
extra_templates:
    
  
extra:
  social:
    - type: 'github'
      link: 'https://github.com/warrieka'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/kay-warrie-7143467/'  
    - type: 'youtube'
      link: 'https://www.youtube.com/channel/UCkDHm_XsA83mARQJnGJFm5g'  
      
markdown_extensions:
  - meta
  - nl2br
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde